name: Auto release
on:
  push:
    branches: [ master ]
jobs:
  check-map-change:
    outputs:
      map_changed: ${{ steps.check_file_changed.outputs.map_changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: check_file_changed
        run: |
          echo "map_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep map_master3.dat)" >> $GITHUB_OUTPUT
  process-map:
    runs-on: ubuntu-latest
    needs: [ check-map-change ]
    if: needs.check-map-change.outputs.map_changed == 'map_master3.dat'
    steps:
      - uses: actions/checkout@v3
      - run: yarn --cwd action
      - id: release
        name: Bump version and release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: ""
          release_name: "Release <RELEASE_VERSION>"
      - run: node action/process.js ${{ steps.release.outputs.tag_name }}
        id: process_map
      - name: Upload process map file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: map_master3.dat
          asset_name: map_master3.dat
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
      - run: node action/page.js
      - name: Upload reader files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: page/data/*.json
          file_glob: true
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
      