name: Auto release
on:
  push:
    branches: [ master ]
jobs:
  check-map-change:
    outputs:
      map_changed: ${{ steps.check_file_changed.outputs.map_changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - shell: pwsh
        id: check_file_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match '^map_master3.dat$' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=map_changed::$HasDiff"
  process-map:
    runs-on: ubuntu-latest
    needs: [ check-map-change ]
    if: needs.check-map-change.outputs.map_changed == 'True'
    steps:
      - uses: actions/checkout@v2
      - run: yarn --cwd action
      - id: release
        name: Bump version and release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: ""
          release_name: "Release <RELEASE_VERSION>"
      - run: node action/process.js ${{ steps.release.outputs.tag_name }}
        id: process_map
      - name: Upload process map file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: map_master3.dat
          asset_name: map_master3.dat
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
      - run: node action/page.js
      - name: Upload reader files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: page/data/*.json
          file_glob: true
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
      